[project]
name = "storyteller"
version = "0.1.0"
description = "A universal conversation creator and dialog manager for games and stories using AI."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
